/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ListRequest {
  NextToken?: string;
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ListResponse {
  NextToken?: string;
  Blogs: BlogSummary[];
}
export interface BlogSummary {
  Id: string;
  Title: string;
  Author: string;
  Summary: string;
  CreationTime: number;
}
